version: "3.9"

services:
  main-login-api:
    build: .
    container_name: main-login-api
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    command: flask run --host=0.0.0.0 --port=5001 --reload
    networks:
      - app-network

networks:
  app-network:
    external: true